name: joincompany
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #ICONOS
  cupertino_icons: ^0.1.2

  #MAPAS
  google_maps: ">=3.0.0 <4.0.0"
  google_maps_flutter: ^0.5.13
  geolocator: ^4.0.3
  google_maps_webservice: ^0.0.14
  http: ^0.12.0+2

  #BASEDEDATOS
  sqflite: ^1.1.5
  path_provider: ^1.0.0
  json_to_form: ^0.0.2

  #Manejo de errores
  sentry: ^2.2.0
  #PATRON BLoC
  rxdart: ^0.21.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true